apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MYSQL_DATABASE: d29ybGRwcmVzc19kYg==
  MYSQL_USER: dG9vcg==
  MYSQL_PASSWORD: cm9vdA==