apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-js-app
  template:
    metadata:
      labels:
        app: node-js-app
    spec:
      containers:
      - name: k8s-app
        image: kod3r/my-nodejs-app:latest
        ports:
        - containerPort: 3000 
        envFrom:
        - configMapRef:
            name: my-node-js-config   
        - secretRef:
            name: my-node-js-secret                
      